### PR TITLE
Improve contributor stats pages

### PR DESCRIPTION
**Pull request by RazvanN7**
- add d rocket logo
    - change background color to purple
    - change text color to white
    - modify the title so that is more self explanatory
    - add useful links to dlang.org and blog post detailing the rewarding system

cc @CyberShadow

### CODE REVIEW

**Comment by CyberShadow** [comment]
Nice. Would you like me to review/test it or just deploy it?

**Comment by RazvanN7** [comment]
@CyberShadow Is this good to go?

**Comment by CyberShadow** [comment]
Ahh sorry I dropped it.

Will look at it today, thanks for the ping.

**Comment by CyberShadow** [comment]
image

What do you think?

**Pull request merged**
