### PR TITLE
Start July-October Bugzilla Cycle

### PR DESCRIPTION
**Pull request by RazvanN7**
@CyberShadow maybe leave this for a couple of days before merging. Thanks!

### CODE REVIEW

**Comment by RazvanN7** [comment]
@CyberShadow I think we can merge this now.

**Review by CyberShadow — APPROVED** [review]

**Comment by RazvanN7** [comment]
@CyberShadow Can you merge this? Thanks!

**Comment by CyberShadow** [comment]
Done and deployed, sorry for missing the last ping!

**Comment by RazvanN7** [comment]
No worries! Thanks!

**Pull request merged**
