### PR TITLE
stop mentioning users when they create a PR

### PR DESCRIPTION
**Pull request by MartinNowak**
- creates notifications that seem fairly pointless given that people just created the PR
- not sure people with mail workflows have a different perspective on this

### CODE REVIEW

**Comment by Geod24** [comment]
Yes please! I never thought about it, but I have mobile notifications for mentions, review requests and the likes, and every time I create a PR I get a pointless notification on my phone. So 100% in favor.

**Review by Geod24 — APPROVED** [review]

**Comment by Geod24** [comment]
Could you fix the tests ? Otherwise LGTM.

**Comment by CyberShadow** [comment]
FYI, this won't stop notifications for most people, because you are automatically subscribed to PRs you create anyway.

The one thing this will change in practice is that it will no longer make the message CC'd to `Mention <mention@noreply.github.com>`. Which would make some email filters a bit simpler, but I don't see any other major effect.

I suggest using Markdown to keep the styling as it was. 

Mention: @CyberShadow 
Not a mention: **@&ZeroWidthSpace;CyberShadow**

**Comment by Geod24** [comment]
> but I don't see any other major effect.

I have the Github app installed on my phone. I get on-screen notifications for mentions, not for other things. That's the default setting.

**Comment by CyberShadow** [comment]
Thanks, that makes a lot of sense.

**Comment by CyberShadow** [comment]
> Could you fix the tests ?

Done

**Pull request merged**
