### PR TITLE
Start April-July bugzilla cycle

### PR DESCRIPTION
**Pull request by RazvanN7**

### CODE REVIEW

**Review by PetarKirov — CHANGES_REQUESTED** [review]
The application shouldn't need to be recompiled (and so no changes to the source code should be necessary) for things like this. I recommend one of two approaches:
* Move the hardcoded dates to environment variables, and simply redeploy the app by setting the new values of the environment variables 
* If every cycle (for the time being) is the same length, you can make the code automatically switch to the new cycle, by checking which is the current cycle by getting the current date. I don't remember the exact rules, but AFAICS it lasts 3 months, so I think you can do something like this:
    ```d
    const monthsPerCycle = 3;
    const date = cast(Date)Clock.currTime;
    const currentCycle = (date.month - Month.jan) / monthsPerCycle;

    const cycleStart = DateTime(
        Date(date.year, 1 + currentCycle * monthsPerCycle, 1),
        TimeOfDay.min
    );
    const cycleEnd = DateTime(
        Date(date.year, (currentCycle + 1) * monthsPerCycle, 1).endOfMonth,
        TimeOfDay.max
    );
    ```
    Note: I'm typing on the phone, so I haven't tested the code and there may be bugs in the logic.

**Comment by PetarKirov** [comment]
ping @RazvanN7

**Comment by RazvanN7** [comment]
@PetarKirov Sorry for the late response, I have been swamped.

The problem with this approach is that the website will start displaying the results for the new cycle immediately after the finish of the last cycle. Usually, I let the previous results hang around for about a week before starting to post the new results. That way, I can simply post the link to the hierarchy and everyone can see the results for a few days after the deadline. If we implement what you are proposing, we would have to make a snapshot of the hierarchy right before the deadline and post it in an alternate way. I guess we could do that. I, personally, don't mind making this sort of PRs every 3 months.

**Comment by RazvanN7** [comment]
@PetarKirov @CyberShadow I think that we should come to a conclusion since the new cycle has already started 12 days ago and we are still presenting the results from the previous cycle.

**Pull request merged**
