### PR TITLE
Start January 2023 - April 2023 Bugzilla Cycle

### PR DESCRIPTION
**Pull request by RazvanN7**

### CODE REVIEW

**Comment by RazvanN7** [comment]
Hmm, the CI is failing with:

```
../../../.dub/packages/ae-0.0.3053/ae/utils/iconv.d(113,29): Error: Bidirectional control characters are disallowed for security reasons.
```

This doesn't seem to have anything to do with the changes in this PR.

**Comment by RazvanN7** [comment]
cc @CyberShadow

**Comment by CyberShadow** [comment]
https://github.com/dlang/dlang-bot/pull/299

Please rebase (and ping me again). Thanks!

**Comment by RazvanN7** [comment]
@CyberShadow done

**Comment by RazvanN7** [comment]
Thanks!

**Pull request merged**
