### PR TITLE
First phase of GitHub Issues support

### PR DESCRIPTION
**Pull request by CyberShadow**
https://forum.dlang.org/post/gebtpqatonfsgkcqptym@forum.dlang.org

Require all contributors to put the word "Bugzilla" before "Issue", so that the bot understands which bug tracking system is being referenced.

### CODE REVIEW

**Comment by burner** [comment]
@CyberShadow Just thought figuring out if its a bugzilla or github issue is going to be a nightmare in the changelog generator, but then I saw this.

Thank you very much!

**Comment by CyberShadow** [comment]
Welcome, let me know when you feel this should go live!

**Comment by burner** [comment]
@CyberShadow could you turn this live please

**Comment by CyberShadow** [comment]
Done. @mdparker Will you handle the announcement?

**Comment by mdparker** [comment]
So what exactly am I announcing? Any reference to a Bugzilla Issue number in a PR title must now say "Bugzilla Issue" instead of just "Issue". Is that correct?

**Comment by mdparker** [comment]
Ah. I see the first item in your forum post now. This is it, yes?

> Update DBot to only accept "Fix Bugzilla" instead of "Fix Issue". Put up a warning if the old string is used.

**Comment by CyberShadow** [comment]
Yep!

**Comment by burner** [comment]
Thank you @CyberShadow @mdparker

**Comment by CyberShadow** [comment]
Thanks!

The announcement: https://forum.dlang.org/post/qhoiyoaptsdfgimuzbwx@forum.dlang.org

**Pull request merged**
