### PR TITLE
dlangbot.bugzilla: Allow matching "Fix issue..." at the start of a line

### PR DESCRIPTION
**Pull request by CyberShadow**
Allow placing the line later in the commit body, instead of requiring it to be at the start of the commit summary.

### CODE REVIEW

**Comment by CyberShadow** [comment]
Running tests locally, I get:

```
[main(ioYn) INF] [github/pull_request](dlang/phobos#4963): action=closed
Remaining expected URLs: ["/github/repos/vibe-d/vibe-core/commits/04b3575c14dc7ad9971e19f153f3e3d712c1bdde/status", "/github/repos/vibe-d/vibe-core/pulls/22/commits", "/github/repos/vibe-d/vibe-core/issues/22/labels", "/github/repos/vibe-d/vibe-core/issues/22/events", "/github/users/wilzbach", "/github/repos/vibe-d/vibe-core/pulls/22/merge"]
Request for unexpected URL received: '/hcloud/servers'
Task terminated with uncaught exception: Reached EOF while searching for end marker.
```

**Comment by CyberShadow** [comment]
`dub test` doesn't run the `dlangbot.bugzilla` unittests, probably due to the failure above, so I can't test this.

**Comment by wilzbach** [comment]
> Running tests locally, I get:

You need to run it in single-mode, e.g. 

```
dub test -- --single --trace
```

**Comment by CyberShadow** [comment]
Thanks!

> 75 test(s) run, 0 failed.

All good, then!

**Pull request merged**
