### PR TITLE
Add gamification webpage display + point calculation logic

### PR DESCRIPTION
**Pull request by RazvanN7**
I haven't tested the actual web page.

cc @CyberShadow

### CODE REVIEW

**Review by CyberShadow — APPROVED** [review]
Let's do it, we can add style later.

**Comment by CyberShadow** [comment]
https://bot.dlang.io/contributor_stats

**Comment by RazvanN7** [comment]
It lives!

**Comment by RazvanN7** [comment]
Thanks @CyberShadow for all your support!

**Comment by RazvanN7** [comment]
Hmm, there is also `dlang` with 100 points, whatever that is.

**Comment by RazvanN7** [comment]
It seems that manually merging (as opposed to using `auto-merge` label) makes it seem that `dlang` was the author of the PR. Looking into it.

**Pull request merged**
